import { createNativeEnemyPathState } from '../core-kernels/native-enemy-pathfinding.ts'
import { createNativeRng } from '../core-kernels/native-rng.ts'
import type { PrimarySpellTransientState } from '../core-kernels/primary-spells.ts'

export type TransientKind = PrimarySpellTransientState['kind']
type TransientOf<Kind extends TransientKind> = Extract<
  PrimarySpellTransientState,
  { kind: Kind }
>

export const TRANSIENT_KINDS = [
  'air',
  'air-hurricane',
  'earth-boulder-bit',
  'earth-called-rock',
  'earth-impact',
  'ether-blast',
  'ether-impact',
  'ether-pierce-streak',
  'fire',
  'fire-ember',
  'fire-explosion',
  'fire-good-imp',
  'fire-impact',
  'fire-patch',
  'player-staff-contact',
  'player-staff-contact-knockback',
  'player-staff-knockback',
  'player-staff-melee',
  'player-staff-move-fade',
  'player-staff-perspective-fade',
  'player-staff-pike-break',
  'player-staff-smoke',
  'player-staff-spin',
  'water',
  'water-aura',
  'water-hail',
  'weld-blizzard-chain-frost',
  'weld-blizzard-glow',
  'weld-boulder-debris',
  'weld-channel',
  'weld-flame-lash-fade',
  'weld-frost-fade',
  'weld-ground-spark-fade',
  'weld-hail-flash',
  'weld-hail-knockback',
  'weld-hail-line',
  'weld-hail-rock-fade',
  'weld-hail-terrain-bouncer',
  'weld-hail-terrain-particle',
  'weld-impact',
  'weld-meteor',
  'weld-meteor-flash',
  'weld-meteor-marker',
  'weld-persistent',
  'weld-steam',
] as const satisfies readonly TransientKind[]

export const registration = { managerLane: 'actor', registrationOrdinal: 7 } as const
export const orientation = [1, 0, 0, 0, 1, 0, 0, 0, 1] as const

function weldBuildId(kind: TransientKind): number {
  if (kind === 'weld-flame-lash-fade') return 1003
  if (kind === 'weld-blizzard-chain-frost'
    || kind === 'weld-blizzard-glow'
    || kind === 'weld-frost-fade') return 1004
  if (kind === 'weld-steam') return 1005
  if (kind === 'weld-boulder-debris') return 1006
  if (kind === 'weld-meteor'
    || kind === 'weld-meteor-flash'
    || kind === 'weld-meteor-marker'
    || kind === 'weld-persistent') return 1007
  if (kind.startsWith('weld-hail')) return 1008
  if (kind === 'weld-ground-spark-fade') return 1009
  return 1000
}

function lightRegistration(kind: TransientKind) {
  return kind === 'air'
    || kind === 'ether-impact'
    || kind === 'fire-ember'
    || kind === 'fire-explosion'
    || kind === 'fire-good-imp'
    || kind === 'fire-impact'
    || kind === 'weld-meteor'
      ? registration
      : null
}

export function transient<Kind extends TransientKind>(
  kind: Kind,
  value = 2,
  overrides: Partial<TransientOf<Kind>> = {},
): TransientOf<Kind> {
  const vector = { x: value, y: value }
  const debris = {
    alpha: value,
    bounceVelocity: value,
    colorGreen: value,
    enhancedShadow: true,
    height: value,
    index: 0,
    position: vector,
    record: 2008,
    rotationDegrees: value,
    rotationStepDegrees: value,
    scale: value,
    velocity: vector,
    verticalVelocity: value,
  } as const
  const path = createNativeEnemyPathState(createNativeRng(42)).state
  const fixture = {
    actionTimingFactor: value,
    activeTicksRemaining: value,
    ageTicks: value,
    alpha: value,
    alphaDecay: value,
    alphaLoss: value,
    alphaMultiplier: value,
    alphaStep: value,
    arcDegrees: value,
    assemblyScale: value,
    atlasPhase: value,
    atlasPhaseStep: value,
    baseProgressPerTick: value,
    baseScale: value,
    birthTick: 0,
    blue: value,
    bodyRotationDeg: value,
    bodyScale: value,
    bodyVariant: 0,
    bounceProgress: value,
    bounceSoundIndex: 1,
    bounceSoundPitch: value,
    bounceSoundSequence: value,
    bounceVelocity: value,
    buildId: weldBuildId(kind),
    burnDamage: value,
    cameraDisplacement: vector,
    charge: value,
    collisionRadius: value,
    colorGreen: value,
    colorRise: value,
    contactAgeTicks: value,
    contactCadence: value,
    contactCharge: value,
    contactDamage: value,
    contactDue: true,
    contactEnabled: true,
    contactOrigin: vector,
    contactScale: value,
    contactSequence: value,
    contactSoundIndex: 1,
    contactSoundPitch: value,
    contactSoundSequence: value,
    contactTicksRemaining: value,
    countdown: value,
    damage: value,
    damageMaximum: value,
    damageMinimum: value,
    debris: kind === 'weld-meteor' ? [debris] : debris,
    delta: vector,
    direction: vector,
    drawAlpha: value,
    durationTicks: 20,
    effectAlpha: value,
    effectPhase: value,
    end: vector,
    endAlpha: value,
    endpoint: vector,
    enhancedEffects: true,
    enhancedShadow: true,
    entry: kind === 'player-staff-move-fade' ? 40 : 15,
    fadeAlpha: value,
    fallHeadingDegrees: value,
    fallHeight: value,
    falling: true,
    fallStep: value,
    fallVelocity: value,
    flightSpeed: value,
    flightTicks: value,
    footprintDimension: value,
    freezeDurationTicks: value,
    frequencyFactor: value,
    growthFactor: value,
    headingDegrees: value,
    height: value,
    hitTargetIds: ['enemy:1'],
    horizontalVelocity: vector,
    hurricaneCharge: value,
    id: 42,
    impactAgeTicks: value,
    impactDue: false,
    impactRadiusScalar: value,
    impactRotationDegrees: value,
    impactSoundPitch: value,
    impactSoundPitches: [value],
    impactSoundVariant: 0,
    impactThrowFirePitch: value,
    impactTicksRemaining: value,
    initialRotationDegrees: value,
    kind,
    lane: 'primary',
    lanes: [{
      angleDegrees: value,
      angularVelocityDegrees: value,
      radius: value,
      verticalOffset: value,
    }],
    lateralMagnitude: value,
    life: value,
    lifeLoss: value,
    lifetimeTicks: 20,
    lifetimeTicksRemaining: value,
    lightGlow: value,
    lightRegistration: lightRegistration(kind),
    maximumScale: value,
    midpoint: vector,
    modifierDurationTicks: value,
    moving: true,
    nativeType: 'moving',
    nextTargetRefreshTick: value,
    obstructionDistance: value,
    obstructionPoint: vector,
    orientation,
    origin: vector,
    outcome: 'normal',
    ownerId: 'wizard',
    painterRegistrations: [{ ...registration, registrationOrdinal: value }],
    parentId: 1,
    path,
    phase: value,
    phaseDegrees: value,
    pikeBreakSoundIndexes: [1],
    position: vector,
    presentation: 'fire',
    presentationRng: createNativeRng(42),
    presentationRotationDegrees: value,
    presentationScale: value,
    privateSeed: 42,
    procSound: null,
    procSoundPitches: [value],
    progress: value,
    pulseDue: false,
    pulseSequence: value,
    pulseTicksRemaining: value,
    pushback: value,
    quantity: value,
    radius: value,
    reacquiresTarget: false,
    record: kind === 'weld-ground-spark-fade' ? 71 : 15,
    releaseAgeTicks: value,
    releaseFadeScale: value,
    remainingDamage: value,
    remainingDistance: value,
    remainingTicks: value,
    rocks: [{
      damageRemaining: value,
      decay: value,
      localPosition: { x: value, y: value, z: value },
      phase: value,
      releaseOffset: vector,
      rockId: 0,
      spriteRecord: 168,
      visualScale: value,
    }],
    rotationDegrees: value,
    rotationStep: value,
    rotationStepDegrees: value,
    savedBounceVelocity: value,
    scale: value,
    shapeSample: value,
    shellScale: value,
    soundPitch: value,
    speed: value,
    speedFactor: value,
    spentEmber: { kind: 'none' },
    start: vector,
    stretch: value,
    strikeTicksRemaining: value,
    supplementalContact: false,
    swooshPitch: value,
    targetHeight: value,
    targetId: 'enemy:1',
    targetIds: ['enemy:1'],
    terminalPosition: vector,
    tint: 0xffffff,
    tintFade: value,
    toughness: value,
    turnSign: 1,
    underpowered: false,
    variant: 0,
    vector: [value, value],
    velocity: vector,
    velocityFactor: value,
    velocityMultiplier: vector,
    verticalOffset: value,
    verticalVelocity: value,
    visualScale: value,
    widen: value,
    width: value,
    worldKey: 'boneyard:test',
    wrapperScalar: value,
    ...overrides,
  }
  return fixture as PrimarySpellTransientState as TransientOf<Kind>
}
