import type { NativeEquipmentModifiers } from '../../core-kernels/native-equipment-effects.ts'
import type { NativeSecondaryActorKind } from '../../core-kernels/native-secondary-abilities.ts'
import type { BoneyardWaveEnemyToken } from '../../core-kernels/boneyard-wave-schema.ts'
import type {
  BoneyardEnemyBrain,
  BoneyardEnemyProjectileKind,
} from '../boneyard-enemy-store.ts'

type EnemyFamily = BoneyardEnemyBrain['family']
export const ML_BOT_POLICY_ENEMY_TOKEN_SPECIES = Object.freeze({
  COFFIN: 'coffin',
  DEMON: 'demon',
  IMP: 'imp',
  PORTAL: 'coffin',
  SKELETON: 'skeleton',
  SKELETONARCHER: 'archer',
  SKELETONMAGE: 'mage',
  WRAITH: 'wraith',
  ZOMBIE: 'zombie',
}) satisfies Readonly<Record<BoneyardWaveEnemyToken, EnemyFamily>>

export const ML_BOT_POLICY_EQUIPMENT_MODIFIER_FAMILIES = Object.freeze({
  castSpeedFlat: 'mobility',
  castSpeedMultiplier: 'mobility',
  classCastSpeedFlat: 'mobility',
  classCastSpeedMultiplier: 'mobility',
  classDamageFlat: 'offense',
  classDamageMultiplier: 'offense',
  classManaCostFlat: 'resource',
  classManaCostMultiplier: 'resource',
  classRecharge: 'resource',
  damageResistance: 'defense',
  featureBits: 'feature',
  globalDamageFlat: 'offense',
  globalDamageMultiplier: 'offense',
  globalManaCostFlat: 'resource',
  globalManaCostMultiplier: 'resource',
  goldMultiplier: 'mobility',
  healthRecovery: 'resource',
  magicResistance: 'defense',
  manaRecovery: 'resource',
  maximumHealth: 'defense',
  maximumMana: 'resource',
  meleeDamageFlat: 'offense',
  meleeDamageMultiplier: 'offense',
  orbPullMultiplier: 'mobility',
  poisonResistance: 'defense',
  recharge: 'resource',
  skillDamageFlat: 'offense',
  skillDamageMultiplier: 'offense',
  walkSpeed: 'mobility',
  weldEffect: 'offense',
}) satisfies Readonly<Record<keyof NativeEquipmentModifiers,
  'defense' | 'feature' | 'mobility' | 'offense' | 'resource'>>

type SecondaryActorClass = 'effect' | 'minion' | 'presentation' | 'status-carrier'

export const ML_BOT_POLICY_SECONDARY_ACTOR_CLASSES = Object.freeze({
  'acid-drop': 'presentation',
  'acid-rain': 'effect',
  'acid-splash': 'presentation',
  comet: 'effect',
  'comet-debris': 'presentation',
  'comet-impact': 'presentation',
  'comet-trail': 'presentation',
  'dampen-wave': 'effect',
  'dampened-projectile': 'presentation',
  'earthquake': 'effect',
  'earthquake-debris': 'presentation',
  'earthquake-dust': 'presentation',
  'earthquake-quake': 'presentation',
  'earthquake-scenery-wobble': 'presentation',
  'electric-burn': 'status-carrier',
  'ether-bolt': 'effect',
  'ether-burn': 'status-carrier',
  'ether-burn-flare': 'presentation',
  'ether-drain': 'effect',
  'ether-drain-capture-flare': 'presentation',
  'ether-drain-cloud': 'presentation',
  'ether-drain-debris': 'presentation',
  'ether-fade': 'presentation',
  'fire-burn': 'status-carrier',
  'fire-burn-flame': 'presentation',
  'fire-patch': 'effect',
  'flash-response-fade': 'presentation',
  'flash-response-grow': 'presentation',
  'freeze-wave': 'effect',
  'freeze-wave-visual': 'presentation',
  'frost-burn-flare': 'presentation',
  golem: 'minion',
  'golem-death': 'presentation',
  'ice-blast': 'effect',
  leviathan: 'effect',
  'leviathan-appendage': 'effect',
  'leviathan-mote': 'presentation',
  'magic-circle': 'effect',
  'magic-circle-player-flash': 'presentation',
  'magic-trap': 'effect',
  'magic-trap-burst': 'effect',
  'magic-trap-shimmer': 'presentation',
  'mindblast-burst': 'effect',
  'mindblast-shockwave': 'effect',
  'moving-fire': 'effect',
  'phase-burst': 'presentation',
  'plane-orb-particle': 'presentation',
  'plane-orb-shot': 'effect',
  'prismatic-wave': 'effect',
  'ring-fire-explosion': 'effect',
  'ring-fire-fragment': 'presentation',
  'shield-break': 'presentation',
  'shield-explosion': 'effect',
  shockwave: 'effect',
  'storm-cloud': 'effect',
  'storm-drop': 'presentation',
  'storm-strike': 'effect',
  'teleport-burst': 'presentation',
  'turn-undead': 'effect',
}) satisfies Readonly<Record<NativeSecondaryActorKind, SecondaryActorClass>>

export const ML_BOT_POLICY_ENEMY_PROJECTILE_CLASSES = Object.freeze({
  arrow: 'projectile',
  'demon-bomb': 'projectile',
  firebolt: 'projectile',
  'guided-missile': 'projectile',
  'poison-pool': 'area',
}) satisfies Readonly<Record<BoneyardEnemyProjectileKind, 'area' | 'projectile'>>
