// Extracted from the twelve retail-generated source files cataloged in
// docs/Game Native Parity RE/spider-native-catalog.json. Preserve command order.
import type { NativeSpiderWaveDefinition } from './native-spider-wave-program.ts'

export function nativeSpiderWaveDefinitions(sourceSha256: string): readonly NativeSpiderWaveDefinition[] {
  const definitions = NATIVE_SPIDER_WAVES[sourceSha256]
  if (!definitions) throw new Error(`Boneyard ${sourceSha256} has no extracted Spider program`)
  return definitions
}

export const NATIVE_SPIDER_WAVES: Readonly<Record<string, readonly NativeSpiderWaveDefinition[]>> = {
  "2118053783606f5ef9dc848671d6eecd8e87aa0a3610c8c2119f08452e15a22f": [
    {"name":"Small Spider Wave","triggerUid":36804,"scriptUid":36803,"startWave":7,"commands":[{"kind":"pause"},{"kind":"spawn-offscreen"},{"kind":"repeat","count":4},{"kind":"spawn","flags":[]},{"kind":"end-repeat"},{"kind":"label"},{"kind":"if-monsters","next":10},{"kind":"sleep","ticks":200},{"kind":"jump","next":5},{"kind":"end-if"},{"kind":"repeat","count":6},{"kind":"spawn","flags":[]},{"kind":"end-repeat"},{"kind":"sleep","ticks":100},{"kind":"label"},{"kind":"if-monsters","next":19},{"kind":"sleep","ticks":200},{"kind":"jump","next":14},{"kind":"end-if"},{"kind":"advance"},{"kind":"unpause"}]},
  ],
  "9e9e1bccd99babf99e190ae4acdae98d1fea2f782b60ba6d45a6b9eae6afe2d9": [
    {"name":"Tiny Spider Wave","triggerUid":36805,"scriptUid":36804,"startWave":6,"commands":[{"kind":"pause"},{"kind":"spawn-offscreen"},{"kind":"repeat","count":2},{"kind":"spawn","flags":[]},{"kind":"end-repeat"},{"kind":"sleep","ticks":100},{"kind":"label"},{"kind":"if-monsters","next":11},{"kind":"sleep","ticks":200},{"kind":"jump","next":6},{"kind":"end-if"},{"kind":"advance"},{"kind":"unpause"}]},
    {"name":"Small Spider Wave","triggerUid":36807,"scriptUid":36806,"startWave":11,"commands":[{"kind":"pause"},{"kind":"spawn-offscreen"},{"kind":"repeat","count":4},{"kind":"spawn","flags":[]},{"kind":"end-repeat"},{"kind":"label"},{"kind":"if-monsters","next":10},{"kind":"sleep","ticks":200},{"kind":"jump","next":5},{"kind":"end-if"},{"kind":"repeat","count":6},{"kind":"spawn","flags":[]},{"kind":"end-repeat"},{"kind":"sleep","ticks":100},{"kind":"label"},{"kind":"if-monsters","next":19},{"kind":"sleep","ticks":200},{"kind":"jump","next":14},{"kind":"end-if"},{"kind":"advance"},{"kind":"unpause"}]},
  ],
  "bd3c38468481b7337b1e7382e5503cc214356906571763a68188b23e821e73fb": [
    {"name":"Small Spider Wave","triggerUid":35003,"scriptUid":35002,"startWave":11,"commands":[{"kind":"pause"},{"kind":"spawn-offscreen"},{"kind":"repeat","count":4},{"kind":"spawn","flags":[]},{"kind":"end-repeat"},{"kind":"label"},{"kind":"if-monsters","next":10},{"kind":"sleep","ticks":200},{"kind":"jump","next":5},{"kind":"end-if"},{"kind":"repeat","count":6},{"kind":"spawn","flags":[]},{"kind":"end-repeat"},{"kind":"sleep","ticks":100},{"kind":"label"},{"kind":"if-monsters","next":19},{"kind":"sleep","ticks":200},{"kind":"jump","next":14},{"kind":"end-if"},{"kind":"advance"},{"kind":"unpause"}]},
    {"name":"Large Spider Wave","triggerUid":35015,"scriptUid":35014,"startWave":27,"commands":[{"kind":"pause"},{"kind":"spawn-offscreen"},{"kind":"repeat","count":6},{"kind":"spawn","flags":["FLAG_HPUP","FLAG_HPUP","FLAG_COCOON"]},{"kind":"end-repeat"},{"kind":"label"},{"kind":"if-monsters","next":10},{"kind":"sleep","ticks":200},{"kind":"jump","next":5},{"kind":"end-if"},{"kind":"repeat","count":7},{"kind":"spawn","flags":["FLAG_HPUP","FLAG_HPUP","FLAG_COCOON"]},{"kind":"end-repeat"},{"kind":"label"},{"kind":"if-monsters","next":18},{"kind":"sleep","ticks":200},{"kind":"jump","next":13},{"kind":"end-if"},{"kind":"repeat","count":4},{"kind":"spawn","flags":["FLAG_HPUP","FLAG_HPUP","FLAG_COCOON","FLAG_COCOON","FLAG_STRONG"]},{"kind":"end-repeat"},{"kind":"sleep","ticks":100},{"kind":"label"},{"kind":"if-monsters","next":27},{"kind":"sleep","ticks":200},{"kind":"jump","next":22},{"kind":"end-if"},{"kind":"advance"},{"kind":"unpause"}]},
  ],
  "8c2f97d2ed54431987e3cb54b7ae3c1098bf1c4517f59ade6aea57759187adb0": [
    {"name":"Tiny Spider Wave","triggerUid":37314,"scriptUid":37313,"startWave":4,"commands":[{"kind":"pause"},{"kind":"spawn-offscreen"},{"kind":"repeat","count":3},{"kind":"spawn","flags":[]},{"kind":"end-repeat"},{"kind":"sleep","ticks":100},{"kind":"label"},{"kind":"if-monsters","next":11},{"kind":"sleep","ticks":200},{"kind":"jump","next":6},{"kind":"end-if"},{"kind":"advance"},{"kind":"unpause"}]},
    {"name":"Small Spider Wave","triggerUid":37316,"scriptUid":37315,"startWave":7,"commands":[{"kind":"pause"},{"kind":"spawn-offscreen"},{"kind":"repeat","count":4},{"kind":"spawn","flags":[]},{"kind":"end-repeat"},{"kind":"label"},{"kind":"if-monsters","next":10},{"kind":"sleep","ticks":200},{"kind":"jump","next":5},{"kind":"end-if"},{"kind":"repeat","count":6},{"kind":"spawn","flags":[]},{"kind":"end-repeat"},{"kind":"sleep","ticks":100},{"kind":"label"},{"kind":"if-monsters","next":19},{"kind":"sleep","ticks":200},{"kind":"jump","next":14},{"kind":"end-if"},{"kind":"advance"},{"kind":"unpause"}]},
  ],
  "bec9377cf539bb193e8af6ad72fa78a5e47e44206a1fef4d6bf3bfbda3f04a08": [
    {"name":"Small Spider Wave","triggerUid":36821,"scriptUid":36820,"startWave":10,"commands":[{"kind":"pause"},{"kind":"spawn-offscreen"},{"kind":"repeat","count":4},{"kind":"spawn","flags":[]},{"kind":"end-repeat"},{"kind":"label"},{"kind":"if-monsters","next":10},{"kind":"sleep","ticks":200},{"kind":"jump","next":5},{"kind":"end-if"},{"kind":"repeat","count":6},{"kind":"spawn","flags":[]},{"kind":"end-repeat"},{"kind":"sleep","ticks":100},{"kind":"label"},{"kind":"if-monsters","next":19},{"kind":"sleep","ticks":200},{"kind":"jump","next":14},{"kind":"end-if"},{"kind":"advance"},{"kind":"unpause"}]},
    {"name":"Large Spider Wave","triggerUid":36833,"scriptUid":36832,"startWave":28,"commands":[{"kind":"pause"},{"kind":"spawn-offscreen"},{"kind":"repeat","count":6},{"kind":"spawn","flags":["FLAG_HPUP","FLAG_HPUP","FLAG_COCOON"]},{"kind":"end-repeat"},{"kind":"label"},{"kind":"if-monsters","next":10},{"kind":"sleep","ticks":200},{"kind":"jump","next":5},{"kind":"end-if"},{"kind":"repeat","count":7},{"kind":"spawn","flags":["FLAG_HPUP","FLAG_HPUP","FLAG_COCOON"]},{"kind":"end-repeat"},{"kind":"label"},{"kind":"if-monsters","next":18},{"kind":"sleep","ticks":200},{"kind":"jump","next":13},{"kind":"end-if"},{"kind":"repeat","count":3},{"kind":"spawn","flags":["FLAG_HPUP","FLAG_HPUP","FLAG_COCOON","FLAG_COCOON","FLAG_STRONG"]},{"kind":"end-repeat"},{"kind":"sleep","ticks":100},{"kind":"label"},{"kind":"if-monsters","next":27},{"kind":"sleep","ticks":200},{"kind":"jump","next":22},{"kind":"end-if"},{"kind":"advance"},{"kind":"unpause"}]},
  ],
  "ec2b27a1415c944c233158da8c21324760cd896e1228143aa18d262f65fa2a45": [
    {"name":"Small Spider Wave","triggerUid":37376,"scriptUid":37375,"startWave":12,"commands":[{"kind":"pause"},{"kind":"spawn-offscreen"},{"kind":"repeat","count":4},{"kind":"spawn","flags":[]},{"kind":"end-repeat"},{"kind":"label"},{"kind":"if-monsters","next":10},{"kind":"sleep","ticks":200},{"kind":"jump","next":5},{"kind":"end-if"},{"kind":"repeat","count":6},{"kind":"spawn","flags":[]},{"kind":"end-repeat"},{"kind":"sleep","ticks":100},{"kind":"label"},{"kind":"if-monsters","next":19},{"kind":"sleep","ticks":200},{"kind":"jump","next":14},{"kind":"end-if"},{"kind":"advance"},{"kind":"unpause"}]},
    {"name":"Large Spider Wave","triggerUid":37388,"scriptUid":37387,"startWave":29,"commands":[{"kind":"pause"},{"kind":"spawn-offscreen"},{"kind":"repeat","count":6},{"kind":"spawn","flags":["FLAG_HPUP","FLAG_HPUP","FLAG_COCOON"]},{"kind":"end-repeat"},{"kind":"label"},{"kind":"if-monsters","next":10},{"kind":"sleep","ticks":200},{"kind":"jump","next":5},{"kind":"end-if"},{"kind":"repeat","count":10},{"kind":"spawn","flags":["FLAG_HPUP","FLAG_HPUP","FLAG_COCOON"]},{"kind":"end-repeat"},{"kind":"label"},{"kind":"if-monsters","next":18},{"kind":"sleep","ticks":200},{"kind":"jump","next":13},{"kind":"end-if"},{"kind":"repeat","count":3},{"kind":"spawn","flags":["FLAG_HPUP","FLAG_HPUP","FLAG_COCOON","FLAG_COCOON","FLAG_STRONG"]},{"kind":"end-repeat"},{"kind":"sleep","ticks":100},{"kind":"label"},{"kind":"if-monsters","next":27},{"kind":"sleep","ticks":200},{"kind":"jump","next":22},{"kind":"end-if"},{"kind":"advance"},{"kind":"unpause"}]},
  ],
  "624b79ae325daa714b24017e0a308c64519f7481eb206e4489968217b1a2e123": [
    {"name":"Small Spider Wave","triggerUid":37385,"scriptUid":37384,"startWave":8,"commands":[{"kind":"pause"},{"kind":"spawn-offscreen"},{"kind":"repeat","count":4},{"kind":"spawn","flags":[]},{"kind":"end-repeat"},{"kind":"label"},{"kind":"if-monsters","next":10},{"kind":"sleep","ticks":200},{"kind":"jump","next":5},{"kind":"end-if"},{"kind":"repeat","count":6},{"kind":"spawn","flags":[]},{"kind":"end-repeat"},{"kind":"sleep","ticks":100},{"kind":"label"},{"kind":"if-monsters","next":19},{"kind":"sleep","ticks":200},{"kind":"jump","next":14},{"kind":"end-if"},{"kind":"advance"},{"kind":"unpause"}]},
  ],
  "e62e5e847562d822382fba14709d5367c9cd7de40f8b4fa52ecea3bfc8d9a430": [
    {"name":"Small Spider Wave","triggerUid":37376,"scriptUid":37375,"startWave":12,"commands":[{"kind":"pause"},{"kind":"spawn-offscreen"},{"kind":"repeat","count":4},{"kind":"spawn","flags":[]},{"kind":"end-repeat"},{"kind":"label"},{"kind":"if-monsters","next":10},{"kind":"sleep","ticks":200},{"kind":"jump","next":5},{"kind":"end-if"},{"kind":"repeat","count":6},{"kind":"spawn","flags":[]},{"kind":"end-repeat"},{"kind":"sleep","ticks":100},{"kind":"label"},{"kind":"if-monsters","next":19},{"kind":"sleep","ticks":200},{"kind":"jump","next":14},{"kind":"end-if"},{"kind":"advance"},{"kind":"unpause"}]},
    {"name":"Huge Spider Wave","triggerUid":37391,"scriptUid":37390,"startWave":40,"commands":[{"kind":"pause"},{"kind":"spawn-offscreen"},{"kind":"repeat","count":15},{"kind":"spawn","flags":["FLAG_HPUP","FLAG_HPUP","FLAG_COCOON"]},{"kind":"end-repeat"},{"kind":"label"},{"kind":"if-monsters","next":10},{"kind":"sleep","ticks":200},{"kind":"jump","next":5},{"kind":"end-if"},{"kind":"repeat","count":7},{"kind":"spawn","flags":["FLAG_HPUP","FLAG_HPUP","FLAG_FAST","FLAG_COCOON"]},{"kind":"end-repeat"},{"kind":"label"},{"kind":"if-monsters","next":18},{"kind":"sleep","ticks":200},{"kind":"jump","next":13},{"kind":"end-if"},{"kind":"repeat","count":13},{"kind":"spawn","flags":["FLAG_HPUP","FLAG_HPUP","FLAG_COCOON","FLAG_COCOON","FLAG_STRONG","FLAG_HPUP","FLAG_FAST","FLAG_FAST","FLAG_COCOON"]},{"kind":"end-repeat"},{"kind":"sleep","ticks":100},{"kind":"label"},{"kind":"if-monsters","next":27},{"kind":"sleep","ticks":200},{"kind":"jump","next":22},{"kind":"end-if"},{"kind":"advance"},{"kind":"unpause"}]},
  ],
  "506200e6f89dd26150c7fcc76f5cddfdb321412657ac979ea5924b567b4a2933": [
    {"name":"Small Spider Wave","triggerUid":37464,"scriptUid":37463,"startWave":11,"commands":[{"kind":"pause"},{"kind":"spawn-offscreen"},{"kind":"repeat","count":4},{"kind":"spawn","flags":[]},{"kind":"end-repeat"},{"kind":"label"},{"kind":"if-monsters","next":10},{"kind":"sleep","ticks":200},{"kind":"jump","next":5},{"kind":"end-if"},{"kind":"repeat","count":6},{"kind":"spawn","flags":[]},{"kind":"end-repeat"},{"kind":"sleep","ticks":100},{"kind":"label"},{"kind":"if-monsters","next":19},{"kind":"sleep","ticks":200},{"kind":"jump","next":14},{"kind":"end-if"},{"kind":"advance"},{"kind":"unpause"}]},
    {"name":"Huge Spider Wave","triggerUid":37479,"scriptUid":37478,"startWave":47,"commands":[{"kind":"pause"},{"kind":"spawn-offscreen"},{"kind":"repeat","count":15},{"kind":"spawn","flags":["FLAG_HPUP","FLAG_HPUP","FLAG_COCOON"]},{"kind":"end-repeat"},{"kind":"label"},{"kind":"if-monsters","next":10},{"kind":"sleep","ticks":200},{"kind":"jump","next":5},{"kind":"end-if"},{"kind":"repeat","count":8},{"kind":"spawn","flags":["FLAG_HPUP","FLAG_HPUP","FLAG_FAST","FLAG_COCOON"]},{"kind":"end-repeat"},{"kind":"label"},{"kind":"if-monsters","next":18},{"kind":"sleep","ticks":200},{"kind":"jump","next":13},{"kind":"end-if"},{"kind":"repeat","count":15},{"kind":"spawn","flags":["FLAG_HPUP","FLAG_HPUP","FLAG_COCOON","FLAG_COCOON","FLAG_STRONG","FLAG_HPUP","FLAG_FAST","FLAG_FAST","FLAG_COCOON"]},{"kind":"end-repeat"},{"kind":"sleep","ticks":100},{"kind":"label"},{"kind":"if-monsters","next":27},{"kind":"sleep","ticks":200},{"kind":"jump","next":22},{"kind":"end-if"},{"kind":"advance"},{"kind":"unpause"}]},
  ],
  "cd4d1ba948ca6624fffb967b02b7c93a6d00cbf9b5ec2c4541330b0616a1c239": [
    {"name":"Tiny Spider Wave","triggerUid":37352,"scriptUid":37351,"startWave":4,"commands":[{"kind":"pause"},{"kind":"spawn-offscreen"},{"kind":"repeat","count":3},{"kind":"spawn","flags":[]},{"kind":"end-repeat"},{"kind":"sleep","ticks":100},{"kind":"label"},{"kind":"if-monsters","next":11},{"kind":"sleep","ticks":200},{"kind":"jump","next":6},{"kind":"end-if"},{"kind":"advance"},{"kind":"unpause"}]},
    {"name":"Small Spider Wave","triggerUid":37354,"scriptUid":37353,"startWave":12,"commands":[{"kind":"pause"},{"kind":"spawn-offscreen"},{"kind":"repeat","count":4},{"kind":"spawn","flags":[]},{"kind":"end-repeat"},{"kind":"label"},{"kind":"if-monsters","next":10},{"kind":"sleep","ticks":200},{"kind":"jump","next":5},{"kind":"end-if"},{"kind":"repeat","count":6},{"kind":"spawn","flags":[]},{"kind":"end-repeat"},{"kind":"sleep","ticks":100},{"kind":"label"},{"kind":"if-monsters","next":19},{"kind":"sleep","ticks":200},{"kind":"jump","next":14},{"kind":"end-if"},{"kind":"advance"},{"kind":"unpause"}]},
  ],
  "efa240ce741df0f781228206d024bb1903c7210d1163eccf80c87e835365422f": [
    {"name":"Small Spider Wave","triggerUid":37328,"scriptUid":37327,"startWave":11,"commands":[{"kind":"pause"},{"kind":"spawn-offscreen"},{"kind":"repeat","count":4},{"kind":"spawn","flags":[]},{"kind":"end-repeat"},{"kind":"label"},{"kind":"if-monsters","next":10},{"kind":"sleep","ticks":200},{"kind":"jump","next":5},{"kind":"end-if"},{"kind":"repeat","count":6},{"kind":"spawn","flags":[]},{"kind":"end-repeat"},{"kind":"sleep","ticks":100},{"kind":"label"},{"kind":"if-monsters","next":19},{"kind":"sleep","ticks":200},{"kind":"jump","next":14},{"kind":"end-if"},{"kind":"advance"},{"kind":"unpause"}]},
    {"name":"Huge Spider Wave","triggerUid":37339,"scriptUid":37338,"startWave":43,"commands":[{"kind":"pause"},{"kind":"spawn-offscreen"},{"kind":"repeat","count":12},{"kind":"spawn","flags":["FLAG_HPUP","FLAG_HPUP","FLAG_COCOON"]},{"kind":"end-repeat"},{"kind":"label"},{"kind":"if-monsters","next":10},{"kind":"sleep","ticks":200},{"kind":"jump","next":5},{"kind":"end-if"},{"kind":"repeat","count":8},{"kind":"spawn","flags":["FLAG_HPUP","FLAG_HPUP","FLAG_FAST","FLAG_COCOON"]},{"kind":"end-repeat"},{"kind":"label"},{"kind":"if-monsters","next":18},{"kind":"sleep","ticks":200},{"kind":"jump","next":13},{"kind":"end-if"},{"kind":"repeat","count":13},{"kind":"spawn","flags":["FLAG_HPUP","FLAG_HPUP","FLAG_COCOON","FLAG_COCOON","FLAG_STRONG","FLAG_HPUP","FLAG_FAST","FLAG_FAST","FLAG_COCOON"]},{"kind":"end-repeat"},{"kind":"sleep","ticks":100},{"kind":"label"},{"kind":"if-monsters","next":27},{"kind":"sleep","ticks":200},{"kind":"jump","next":22},{"kind":"end-if"},{"kind":"advance"},{"kind":"unpause"}]},
  ],
  "1be4c308ccd442d70060cc66e3daa7b073faf035fd92d6b49fad4c33a91ef0c1": [
    {"name":"Small Spider Wave","triggerUid":37390,"scriptUid":37389,"startWave":12,"commands":[{"kind":"pause"},{"kind":"spawn-offscreen"},{"kind":"repeat","count":4},{"kind":"spawn","flags":[]},{"kind":"end-repeat"},{"kind":"label"},{"kind":"if-monsters","next":10},{"kind":"sleep","ticks":200},{"kind":"jump","next":5},{"kind":"end-if"},{"kind":"repeat","count":6},{"kind":"spawn","flags":[]},{"kind":"end-repeat"},{"kind":"sleep","ticks":100},{"kind":"label"},{"kind":"if-monsters","next":19},{"kind":"sleep","ticks":200},{"kind":"jump","next":14},{"kind":"end-if"},{"kind":"advance"},{"kind":"unpause"}]},
    {"name":"Large Spider Wave","triggerUid":37402,"scriptUid":37401,"startWave":34,"commands":[{"kind":"pause"},{"kind":"spawn-offscreen"},{"kind":"repeat","count":6},{"kind":"spawn","flags":["FLAG_HPUP","FLAG_HPUP","FLAG_COCOON"]},{"kind":"end-repeat"},{"kind":"label"},{"kind":"if-monsters","next":10},{"kind":"sleep","ticks":200},{"kind":"jump","next":5},{"kind":"end-if"},{"kind":"repeat","count":8},{"kind":"spawn","flags":["FLAG_HPUP","FLAG_HPUP","FLAG_COCOON"]},{"kind":"end-repeat"},{"kind":"label"},{"kind":"if-monsters","next":18},{"kind":"sleep","ticks":200},{"kind":"jump","next":13},{"kind":"end-if"},{"kind":"repeat","count":3},{"kind":"spawn","flags":["FLAG_HPUP","FLAG_HPUP","FLAG_COCOON","FLAG_COCOON","FLAG_STRONG"]},{"kind":"end-repeat"},{"kind":"sleep","ticks":100},{"kind":"label"},{"kind":"if-monsters","next":27},{"kind":"sleep","ticks":200},{"kind":"jump","next":22},{"kind":"end-if"},{"kind":"advance"},{"kind":"unpause"}]},
    {"name":"Huge Spider Wave","triggerUid":37407,"scriptUid":37406,"startWave":49,"commands":[{"kind":"pause"},{"kind":"spawn-offscreen"},{"kind":"repeat","count":13},{"kind":"spawn","flags":["FLAG_HPUP","FLAG_HPUP","FLAG_COCOON"]},{"kind":"end-repeat"},{"kind":"label"},{"kind":"if-monsters","next":10},{"kind":"sleep","ticks":200},{"kind":"jump","next":5},{"kind":"end-if"},{"kind":"repeat","count":6},{"kind":"spawn","flags":["FLAG_HPUP","FLAG_HPUP","FLAG_FAST","FLAG_COCOON"]},{"kind":"end-repeat"},{"kind":"label"},{"kind":"if-monsters","next":18},{"kind":"sleep","ticks":200},{"kind":"jump","next":13},{"kind":"end-if"},{"kind":"repeat","count":13},{"kind":"spawn","flags":["FLAG_HPUP","FLAG_HPUP","FLAG_COCOON","FLAG_COCOON","FLAG_STRONG","FLAG_HPUP","FLAG_FAST","FLAG_FAST","FLAG_COCOON"]},{"kind":"end-repeat"},{"kind":"sleep","ticks":100},{"kind":"label"},{"kind":"if-monsters","next":27},{"kind":"sleep","ticks":200},{"kind":"jump","next":22},{"kind":"end-if"},{"kind":"advance"},{"kind":"unpause"}]},
  ],
}
